# 基于python:3.11-slim构建
FROM python:3.11-slim

WORKDIR /app

# 安装依赖
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# 拷贝server代码
COPY server.py ./
COPY templates ./templates

EXPOSE 5000

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "5000", "--reload", "--log-level", "info"]
