name: 百聆（bailing）
version: 1.0

logging:
  level: debug

# 唤醒词
WakeWord: 百聆

interrupt: false
# 具体处理时选择的模块
selected_module:
  Recorder: RecorderPyAudio
  ASR: FunASR
  VAD: SileroVAD
  LLM: OpenAILLM
  TTS: EdgeTTS
  Player: PygameSoundPlayer

Recorder:
  RecorderPyAudio:
    output_file: tmp/

ASR:
  FunASR:
    model_dir: FunAudioLLM/SenseVoiceSmall
    output_file: tmp/

VAD:
  SileroVAD:
    sampling_rate: 16000
    threshold: 1
    min_silence_duration_ms: 200 # 如果说话停顿比较长，可以把这个值设置大一些

LLM:
  OpenAILLM:
    model_name: deepseek-chat
    url: https://api.deepseek.com
    api_key:

TTS:
  MacTTS:
    voice: Tingting
    output_file: tmp/
  EdgeTTS:
    voice: zh-CN-XiaoxiaoNeural
    output_file: tmp/
  GTTS:
    lang: zh
    output_file: tmp/
  CosyvoiceTTS:
    output_file: tmp/
  CHATTTS:
    output_file: tmp/
  KOKOROTTS:
    output_file: tmp/
    lang: z
    voice: zm_yunyang

Player:
  PygameSoundPlayer: null
  PygamePlayer: null
  CmdPlayer: null
  PyaudioPlayer: null

Memory:
  dialogue_history_path: tmp/
  memory_file: tmp/memory.json
  model_name: deepseek-chat
  url: https://api.deepseek.com
  api_key: null

TaskManager:
  functions_call_name: plugins/function_calls_config.json
  aigc_manus_enabled: false
