name: Build and Push Builder Docker Image

on:
  push:
    branches:
      - main
      - master
    paths:
      - "docker/dockerfile.dev"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/docker-build-builder.yml"
    tags:
      - "builder-v*"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "docker/dockerfile.dev"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/docker-build-builder.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-builder

jobs:
  build-and-push-builder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for builder image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-builder
            type=ref,event=pr,suffix=-builder
            type=semver,pattern={{version}},prefix=builder-
            type=semver,pattern={{major}}.{{minor}},prefix=builder-
            type=semver,pattern={{major}},prefix=builder-
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=builder-{{branch}}-

      - name: Build and push Builder Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfile.dev
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=builder
          cache-to: type=gha,mode=max,scope=builder
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Output image tags
        run: |
          echo "Builder image tags:"
          echo "${{ steps.meta.outputs.tags }}"
