name: Build and Push Builder Docker Image (Multi-arch)

on:
  push:
    branches:
      - main
      - master
    paths:
      - "docker/dockerfile.dev"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/docker-build-builder.yml"
    tags:
      - "builder-v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-builder

jobs:
  build-and-push-builder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo docker system prune -af

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file ./docker/dockerfile.dev \
            --target builder \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            --cache-from type=gha,scope=builder \
            --cache-to type=gha,mode=max,scope=builder \
            --push .
